# Start FROM Nvidia PyTorch image https://ngc.nvidia.com/catalog/containers/nvidia:pytorch
FROM nvcr.io/nvidia/pytorch:21.03-py3

# Install linux packages
RUN apt update && apt install -y zip htop screen libgl1-mesa-glx

# Install python dependencies
COPY requirements.txt .
RUN python -m pip install --upgrade pip
RUN pip install torch==1.13.0
RUN pip uninstall -y nvidia-tensorboard nvidia-tensorboard-plugin-dlprof
RUN pip install --no-cache -r requirements.txt coremltools onnx gsutil notebook

# Create working directory
RUN mkdir -p /mount/src/yolov5-streamlit-app
WORKDIR /mount/src/yolov5-streamlit-app/

# Copy contents
COPY . /mount/src/yolov5-streamlit-app/

# Set environment variables
ENV HOME=/home/adminuser/venv
