name: My CI/CD Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install libGL.so.1
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx
      if: runner.os == 'Linux'  # Chỉ cài đặt trên hệ thống Linux

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run your script
      run: python your_script.py
